
  // Fonction pour calculer le temps de lecture
  function calculateReadingTime(articleContent) {
    const wordsPerMinute = 225; // Vitesse moyenne de lecture
    const wordCount = articleContent.split(/\s+/).length; // Compte les mots
    return Math.ceil(wordCount / wordsPerMinute); // Temps en minutes
  }

  // Contenu de l'article
  const articleContent = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.
Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi. Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.
Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi. Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.Découvrez comment alléger votre routine quotidienne avec seulement 3 produits efficaces. Moins d’emballages, moins de stress, plus de sérénité. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae eveniet alias laborum hic, veritatis animi nihil repellendus! Veritatis quas iusto atque illo recusandae neque odio nihil sunt aspernatur! Sint, nihil.
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis, sint quod unde beatae magni, itaque amet dicta laborum earum sequi atque assumenda consequuntur non a nisi aut. Earum, aspernatur eligendi.`;

  // Calcul du temps de lecture
  const readingTime = calculateReadingTime(articleContent);

  // Affichage dans le DOM
  document.getElementById('reading-time').textContent = `${readingTime} minutes`;